#! /bin/sh


############# Auto Start Scripts
$HOME/.config/bspwm/Autostart.sh
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/auto-presel.sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
   


############ BORDER COLORS #####################

##### Gray Border
bspc config normal_border_color "#434C5E"
bspc config active_border_color "#434C5E"
bspc config focused_border_color "#D8DEE9"







############## Applications Rules ##############



bspc rule -a code desktop='^1'
bspc rule -a Spotify state=floating desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Rambox state=tiled desktop='^4'
bspc rule -a Steam state=floating desktop='^5'



bspc rule -a obs desktop='^7'

####### Digital Painting #########
bspc rule -a Gimp-2.10 desktop='^8' 



###### Workspace 9 (System Settings)
bspc rule -a Barrier state=tiled desktop='^9'
bspc rule -a Pavucontrol desktop='^9'



########################
###### WORKSPACE #######
######################## 



#### WK 1 - Dev
#### WK 2 - Music 
#### WK 3 - Discord 
#### WK 4 - Email
#### WK 5 - Steam
#### WK 6 - Anime
#### WK 7 - obs
#### wk 8 - gimp
#### WK 9 - pavu control & barrier



##################################
####### AUTO START PROGRAMS ######
nitrogen --restore; sleep 1 &
picom --config ~/.config/picom.conf &
pavucontrol & barrier

##### DEFAULT COMMANDS

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

