#! /bin/sh


############# Auto Start Scripts
$HOME/.config/bspwm/Autostart.sh
$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/auto-presel.sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
   


############ BORDER COLORS #####################


bspc config normal_border_color "#ed91c1"
bspc config active_border_color "#ed91c1"
bspc config focused_border_color "#f76ab3"




############## Applications Rules ##############





bspc rule -a dotnet desktop='^3'
bspc rule -a Steam state=floating desktop='^4'
bspc rule -a obs desktop='^7'
bspc rule -a Gimp-2.10 desktop='^8' 
bspc rule -a Pavucontrol desktop='^9'
#bspc rule -a Chromium desktop='^2'


########################
###### WORKSPACE #######
######################## 



#### WK 1 - DEV
#### WK 2 - MUSIC 
#### WK 3 - OSU 
#### WK 4 - STEAM
#### WK 5 - ANIME
#### WK 6 - MAIL
#### WK 7 - obs
#### wk 8 - gimp
#### WK 9 - pavu control



##################################
####### AUTO START PROGRAMS ######
nitrogen --restore; sleep 1 &
picom --config ~/.config/picom.conf &
pavucontrol


##### DEFAULT COMMANDS

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

